//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPhamDienTu_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int maBanner { get; set; }
        public string fileBanner { get; set; }
        public Nullable<bool> kichHoat { get; set; }
        public string ghiChu { get; set; }
    }
}
