//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPhamDienTu_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public DanhMuc()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int maDanhMuc { get; set; }
        public string tenDanhMuc { get; set; }
        public Nullable<int> maNhaSanXuat { get; set; }
        public string ghiChu { get; set; }
        public string logoTungDanhMucSP { get; set; }
    
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
