//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPhamDienTu_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
        }
    
        public int maHoaDon { get; set; }
        public Nullable<System.DateTime> ngayBan { get; set; }
        public Nullable<int> maKhachHang { get; set; }
        public Nullable<decimal> tienBan { get; set; }
        public Nullable<double> giamGia { get; set; }
        public Nullable<decimal> tongTien { get; set; }
        public string ghiChu { get; set; }
        public Nullable<int> maNguoiDung { get; set; }
    
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
