//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPhamDienTu_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public NguoiDung()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int maNguoiDung { get; set; }
        public string tenNguoiDung { get; set; }
        public string tenDangNhap { get; set; }
        public string matKhau { get; set; }
        public string diaChi { get; set; }
        public string soDienThoai { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> ngayVaoLam { get; set; }
        public Nullable<bool> maPhanQuyen { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
