//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanPhamDienTu_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int maTinTuc { get; set; }
        public string tenTinTuc { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public string anhMinhHoa { get; set; }
        public Nullable<bool> kichHoat { get; set; }
        public string ghiChu { get; set; }
        public Nullable<int> maLoaiTin { get; set; }
    
        public virtual LoaiTinTuc LoaiTinTuc { get; set; }
    }
}
